
apiVersion: v1
kind: Service
metadata:
  name: http-service
  labels:
    app: httpServerTest
    pipeline: test
    version: v1
spec:
  type: NodePort
  ports:
  - name: port
    port: 9099
    nodePort: 30000
    targetPort: 9099
  selector:
    app: httpServerTest